### ISSUE TITLE
Create bucketListView within client/views folder

### ISSUE THREAD

**Issue by PMGH** [PMGH/bucket-list#13]
Views folder
	- server.js
	- bucketListView
	- app.js

**Comment by PMGH** [comment]
Populate 'ul' in index.html :)

**Comment by ghost** [comment]
- I've called the file chosenCountryView
- our variable is chosenCountry, as agreed
- this view is just the bare bones right now - I've only given the chosenCountry a name

**Comment by ghost** [comment]
resolves #13
